# Generated by Django 3.1.4 on 2021-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
